/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Vinh
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TRANGCHU = new javax.swing.JPanel();
        jbtn_hosohocsinh = new javax.swing.JButton();
        jbtn_danhsachlop = new javax.swing.JButton();
        jbtn_danhsachhocsinh = new javax.swing.JButton();
        jbtn_bangdiemmonhoc = new javax.swing.JButton();
        jbtn_baocaotongketmon = new javax.swing.JButton();
        jbtn_baocaotongkethocky = new javax.swing.JButton();
        jbtn_baocaotongketmon1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang Chủ");

        TRANGCHU.setBackground(new java.awt.Color(153, 255, 255));
        TRANGCHU.setToolTipText("TRANG CHỦ");

        jbtn_hosohocsinh.setBackground(new java.awt.Color(255, 102, 0));
        jbtn_hosohocsinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtn_hosohocsinh.setText("HỒ SƠ HỌC SINH");
        jbtn_hosohocsinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_hosohocsinhActionPerformed(evt);
            }
        });

        jbtn_danhsachlop.setBackground(new java.awt.Color(255, 102, 0));
        jbtn_danhsachlop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtn_danhsachlop.setText("DANH SÁCH LỚP");
        jbtn_danhsachlop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_danhsachlopActionPerformed(evt);
            }
        });

        jbtn_danhsachhocsinh.setBackground(new java.awt.Color(255, 102, 0));
        jbtn_danhsachhocsinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtn_danhsachhocsinh.setText("DANH SÁCH HỌC SINH");
        jbtn_danhsachhocsinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_danhsachhocsinhActionPerformed(evt);
            }
        });

        jbtn_bangdiemmonhoc.setBackground(new java.awt.Color(255, 102, 0));
        jbtn_bangdiemmonhoc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtn_bangdiemmonhoc.setText("BẢNG ĐIỂM MÔN HỌC");
        jbtn_bangdiemmonhoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_bangdiemmonhocActionPerformed(evt);
            }
        });

        jbtn_baocaotongketmon.setBackground(new java.awt.Color(255, 102, 0));
        jbtn_baocaotongketmon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtn_baocaotongketmon.setText("THÊM TÀI KHOẢN");
        jbtn_baocaotongketmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_baocaotongketmonActionPerformed(evt);
            }
        });

        jbtn_baocaotongkethocky.setBackground(new java.awt.Color(255, 102, 0));
        jbtn_baocaotongkethocky.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtn_baocaotongkethocky.setText("BÁO CÁO TỔNG KẾT HỌC KỲ");
        jbtn_baocaotongkethocky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_baocaotongkethockyActionPerformed(evt);
            }
        });

        jbtn_baocaotongketmon1.setBackground(new java.awt.Color(255, 102, 0));
        jbtn_baocaotongketmon1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtn_baocaotongketmon1.setText("BÁO CÁO TỔNG KẾT MÔN");
        jbtn_baocaotongketmon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_baocaotongketmon1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("MÔN HỌC");

        javax.swing.GroupLayout TRANGCHULayout = new javax.swing.GroupLayout(TRANGCHU);
        TRANGCHU.setLayout(TRANGCHULayout);
        TRANGCHULayout.setHorizontalGroup(
            TRANGCHULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TRANGCHULayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(TRANGCHULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TRANGCHULayout.createSequentialGroup()
                        .addComponent(jbtn_hosohocsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(jbtn_danhsachlop, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(jbtn_danhsachhocsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TRANGCHULayout.createSequentialGroup()
                        .addGroup(TRANGCHULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_bangdiemmonhoc, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                        .addGap(81, 81, 81)
                        .addGroup(TRANGCHULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TRANGCHULayout.createSequentialGroup()
                                .addComponent(jbtn_baocaotongketmon1)
                                .addGap(81, 81, 81)
                                .addComponent(jbtn_baocaotongkethocky))
                            .addComponent(jbtn_baocaotongketmon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        TRANGCHULayout.setVerticalGroup(
            TRANGCHULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TRANGCHULayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(TRANGCHULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_hosohocsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_danhsachlop, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_danhsachhocsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(TRANGCHULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_bangdiemmonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_baocaotongketmon1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_baocaotongkethocky, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(TRANGCHULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtn_baocaotongketmon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TRANGCHU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TRANGCHU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TRANGCHU.getAccessibleContext().setAccessibleParent(TRANGCHU);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_hosohocsinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_hosohocsinhActionPerformed
        // TODO add your handling code here:
        HoSoHocSinh ct = new HoSoHocSinh();
        ct.setLocationRelativeTo(null);
        ct.setVisible(true);
    }//GEN-LAST:event_jbtn_hosohocsinhActionPerformed

    private void jbtn_bangdiemmonhocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_bangdiemmonhocActionPerformed
        // TODO add your handling code here:
        BangDiemMonHoc ct = new BangDiemMonHoc();
        ct.setLocationRelativeTo(null);
        ct.setVisible(true);
    }//GEN-LAST:event_jbtn_bangdiemmonhocActionPerformed

    private void jbtn_baocaotongketmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_baocaotongketmonActionPerformed
        // TODO add your handling code here:
         BaoCaoTongKetMon ct = new BaoCaoTongKetMon();
        ct.setLocationRelativeTo(null);
        ct.setVisible(true);
    }//GEN-LAST:event_jbtn_baocaotongketmonActionPerformed

    private void jbtn_danhsachlopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_danhsachlopActionPerformed
        // TODO add your handling code here:
        DanhSachLop ct = new DanhSachLop();
        ct.setLocationRelativeTo(null);
        ct.setVisible(true);
    }//GEN-LAST:event_jbtn_danhsachlopActionPerformed

    private void jbtn_danhsachhocsinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_danhsachhocsinhActionPerformed
        // TODO add your handling code here:
        HoSoHocSinh ct = new HoSoHocSinh();
        ct.setLocationRelativeTo(null);
        ct.setVisible(true);
    }//GEN-LAST:event_jbtn_danhsachhocsinhActionPerformed

    private void jbtn_baocaotongkethockyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_baocaotongkethockyActionPerformed
        // TODO add your handling code here:
        BaoCaoTongKetHocKy ct = new BaoCaoTongKetHocKy();
        ct.setLocationRelativeTo(null);
        ct.setVisible(true);
    }//GEN-LAST:event_jbtn_baocaotongkethockyActionPerformed

    private void jbtn_baocaotongketmon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_baocaotongketmon1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_baocaotongketmon1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TRANGCHU;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jbtn_bangdiemmonhoc;
    private javax.swing.JButton jbtn_baocaotongkethocky;
    private javax.swing.JButton jbtn_baocaotongketmon;
    private javax.swing.JButton jbtn_baocaotongketmon1;
    private javax.swing.JButton jbtn_danhsachhocsinh;
    private javax.swing.JButton jbtn_danhsachlop;
    private javax.swing.JButton jbtn_hosohocsinh;
    // End of variables declaration//GEN-END:variables
}
